repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: fix-byte-order-marker
    - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/pycqa/pylint
  rev: v2.15.2
  hooks:
    - id: pylint
      additional_dependencies: ['pylint_fixme_info']
- repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
- repo: local
  # mypy needs to run in our venv, so use a system-type hook
  hooks:
    - id: mypy
      name: mypy
      entry: env MYPYPATH=stubs/ mypy
      language: system
      types_or: [python, pyi]
exclude: alembic/.*|example.py
