"""empty message

Revision ID: 317f22eaeb7b
Revises: ebc0580f9634
Create Date: 2023-06-12 20:40:56.939004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317f22eaeb7b'
down_revision = 'ebc0580f9634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.String(), nullable=True))
    op.add_column('group', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_column('group', 'description')
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
