version = 1
disable_existing_loggers = false
[formatters.default]
format = '%(asctime)s %(levelname)s %(name)s:%(lineno)d - %(message)s'
datefmt = '%Y-%m-%d %H:%M:%S'

[handlers.console]
class = "logging.StreamHandler"
formatter = "default"
stream = "ext://sys.stderr"

# module specific log levels go here
[loggers."uvicorn.error"]
propagate = false
level = "ERROR"
handlers = ["console"]

[root]
level = "WARNING"
handlers = ["console"]
